export const pokemonData =[
    {id: 1, name: 'Bulbasaur', type: 'grass', level: 1},
    {id: 4, name: 'Charmander', type: 'fire', level: 1},
    {id: 7, name: 'Squirtle', type: 'water', level: 1},
    {id: 10, name: 'Caterpie', type: 'bug', level: 1},
    {id: 23, name: 'Ekans', type: 'poison', level: 1},
    {id: 25, name: 'Pikachu', type: 'electric', level: 1},
    {id: 27, name: 'Sandshrew', type: 'ground', level: 1},
    // {id: 35, name: 'Clefairy', type: 'fairy', level: 1},
    {id: 63, name: 'Abra', type: 'psychic', level: 1},
    {id: 66, name: 'Machop', type: 'fighting', level: 1},
    {id: 92, name: 'Gastly', type: 'ghost', level: 1},
    {id: 133, name: 'Eevee', type: 'normal', level: 1},
    {id: 147, name: 'Dratini', type: 'dragon', level: 1},    
]
